// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrlSRZK14pa1hLoj4ZwIhxUCPn2Fw3NI',
    appId: '1:26070783383:web:19e8d7359908480c5ca0d2',
    messagingSenderId: '26070783383',
    projectId: 'project-radar-72d02',
    authDomain: 'project-radar-72d02.firebaseapp.com',
    storageBucket: 'project-radar-72d02.firebasestorage.app',
    measurementId: 'G-YLCYW574ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQ7oSt2AxBHjNMV88dMse9tyREz3wVS0',
    appId: '1:26070783383:android:97be73b6a2d515395ca0d2',
    messagingSenderId: '26070783383',
    projectId: 'project-radar-72d02',
    storageBucket: 'project-radar-72d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV6J_g1XCuDgLjkg0phutTOfdZlPTpW_A',
    appId: '1:26070783383:ios:99cf54f091816a235ca0d2',
    messagingSenderId: '26070783383',
    projectId: 'project-radar-72d02',
    storageBucket: 'project-radar-72d02.firebasestorage.app',
    iosBundleId: 'com.example.radarDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV6J_g1XCuDgLjkg0phutTOfdZlPTpW_A',
    appId: '1:26070783383:ios:99cf54f091816a235ca0d2',
    messagingSenderId: '26070783383',
    projectId: 'project-radar-72d02',
    storageBucket: 'project-radar-72d02.firebasestorage.app',
    iosBundleId: 'com.example.radarDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANrlSRZK14pa1hLoj4ZwIhxUCPn2Fw3NI',
    appId: '1:26070783383:web:5b3dfe7367002b4a5ca0d2',
    messagingSenderId: '26070783383',
    projectId: 'project-radar-72d02',
    authDomain: 'project-radar-72d02.firebaseapp.com',
    storageBucket: 'project-radar-72d02.firebasestorage.app',
    measurementId: 'G-LV0DQE4ZEN',
  );
}
